#!/usr/bin/env python3
"""Regenerate plan/PIPELINE.md from artifact frontmatter.

Walks plan/ and any plan-mod-*/ for *.md files, parses the YAML-ish
frontmatter (no PyYAML dependency), and emits a status table grouped
by artifact type.

Source of truth = each artifact's frontmatter. This script never writes
to artifact files; it only writes plan/PIPELINE.md.

Usage: python3 scripts/regen-pipeline.py
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "plan" / "PIPELINE.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
KEY_BLOCK_RE = re.compile(r"^([a-zA-Z_][a-zA-Z0-9_]*):\s*$")
KEY_VALUE_RE = re.compile(r"^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$")
LIST_ITEM_RE = re.compile(r"^\s+-\s+(.*)$")

TYPE_ORDER = [
    "vision",
    "research",
    "epic",
    "arch",
    "adr",
    "schema",
    "audit",
    "tasks",
    "agent",
    "standard",
]


def parse_frontmatter(text: str) -> dict | None:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    fm: dict = {}
    lines = m.group(1).split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        block = KEY_BLOCK_RE.match(line)
        if block:
            key = block.group(1)
            items: list[str] = []
            i += 1
            while i < len(lines) and LIST_ITEM_RE.match(lines[i]):
                items.append(LIST_ITEM_RE.match(lines[i]).group(1).strip())
                i += 1
            fm[key] = items
            continue
        kv = KEY_VALUE_RE.match(line)
        if kv:
            key, val = kv.group(1), kv.group(2).strip()
            if val.startswith("[") and val.endswith("]"):
                inner = val[1:-1].strip()
                fm[key] = (
                    [x.strip() for x in inner.split(",") if x.strip()] if inner else []
                )
            else:
                fm[key] = val
            i += 1
            continue
        i += 1
    return fm


def collect_artifacts() -> list[tuple[Path, dict]]:
    roots = [REPO / "plan"]
    for entry in REPO.iterdir():
        if entry.is_dir() and entry.name.startswith("plan-mod-"):
            roots.append(entry)
    artifacts: list[tuple[Path, dict]] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*.md"):
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                continue
            fm = parse_frontmatter(text)
            if not fm or "artifact_id" not in fm or "type" not in fm:
                continue
            artifacts.append((path, fm))
    return artifacts


def fmt_list(value) -> str:
    if isinstance(value, list):
        return ", ".join(value) if value else "—"
    if not value:
        return "—"
    return str(value)


def emit(artifacts: list[tuple[Path, dict]]) -> str:
    by_type: dict[str, list[tuple[Path, dict]]] = {}
    for path, fm in artifacts:
        by_type.setdefault(fm.get("type", "unknown"), []).append((path, fm))
    for items in by_type.values():
        items.sort(key=lambda pf: pf[1].get("artifact_id", ""))

    lines: list[str] = []
    lines.append("# Pipeline Status")
    lines.append("")
    lines.append(
        "> Generated by `scripts/regen-pipeline.py` from artifact frontmatter. **Do not edit by hand** — re-run the script."
    )
    lines.append(f"> Last regenerated: {date.today().isoformat()}.")
    lines.append("")
    lines.append(
        f"Total artifacts: **{len(artifacts)}**, grouped by type. Source of truth lives in each artifact's frontmatter."
    )
    lines.append("")
    lines.append("## Status legend")
    lines.append("")
    lines.append(
        "`draft` = work in progress · `review` = awaiting downstream/human approval · `proposed` = ADR awaiting acceptance · `approved` / `accepted` = ready for downstream consumption · `superseded` = replaced by a newer artifact."
    )
    lines.append("")

    seen = set()
    for t in TYPE_ORDER:
        if t in by_type:
            seen.add(t)
            emit_section(lines, t, by_type[t])
    for t in sorted(by_type):
        if t not in seen:
            emit_section(lines, t, by_type[t])

    return "\n".join(lines) + "\n"


def emit_section(lines: list[str], t: str, items: list[tuple[Path, dict]]) -> None:
    lines.append(f"## {t.title()} `{len(items)}`")
    lines.append("")
    lines.append("| id | status | upstream | downstream | updated |")
    lines.append("|---|---|---|---|---|")
    for path, fm in items:
        rel = path.relative_to(REPO).as_posix()
        if rel.startswith("plan/"):
            link_target = rel[len("plan/") :]
        else:
            link_target = "../" + rel
        link = f"[`{fm['artifact_id']}`]({link_target})"
        lines.append(
            f"| {link} | `{fm.get('status', '—')}` | {fmt_list(fm.get('upstream'))} | {fmt_list(fm.get('downstream'))} | {fm.get('updated', '—')} |"
        )
    lines.append("")


def main() -> int:
    artifacts = collect_artifacts()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(emit(artifacts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(artifacts)} artifacts).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
